### ISSUE TITLE
Context for GO-CAM

### ISSUE THREAD

**Issue by lpalbou** [prefixcommons/biocontext#16]
We already have a context for GO Terms:
https://github.com/prefixcommons/biocontext/blob/624fbbfac12874df16e5d841170e9d4c0a3806b4/registry/go_context.jsonld#L11

But we don't have a context for GO CAMs, so we can't convert 
http://model.geneontology.org/57c82fad00000784 <-> gomodel:57c82fad00000784

Proposal: 
* since we are using gomodel:xxx everywhere, add:
 "gomodel": "http://model.geneontology.org/", 
* alternatively, change all the references to gomodel:xxx to a more standard:
 "GOCAM": "http://model.geneontology.org/",

**Comment by cmungall** [comment]
+1 

can you make a PR on https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

**Comment by lpalbou** [comment]
Done. 

@cmungall when will db-xrefs will be used to regenerate [go_context.jsonld](https://github.com/prefixcommons/biocontext/blob/master/registry/go_context.jsonld) ? I suppose with the monthly release ?
